version: '3'

services:
  nginx:
    image: nginx:1.15-alpine
    restart: unless-stopped
    volumes:
      - ./certs:/certs
      - ./html:/html
      - ./data/conf.d:/etc/nginx/conf.d
    ports:
      - "443:443"
